***WELCOME TO NUMPY***


In [1]:
import numpy as np

In [2]:
myary=np.array([[3,6,5,7]]),

In [3]:
myary

(array([[3, 6, 5, 7]]),)

# Array creation:Conversion from other Python structures

In [6]:
listary=np.array([[1,2,3],[3,4,5],[6,7,8]])

In [8]:
listary

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
listary.dtype

dtype('int32')

In [11]:
listary.size

9

In [12]:
listary.shape

(3, 3)

In [15]:
listary[2][0]

6

# Intrinsic numpy array creation object

In [16]:
zeros=np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.dtype


dtype('float64')

In [19]:
zeros.shape

(2, 5)

In [20]:
rng=np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])