In [1]:
import numpy as np

In [2]:
lspace=np.linspace(1,50,10)

In [3]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [9]:
lsspace=np.linspace(1,4,4)


In [10]:
lsspace

array([1., 2., 3., 4.])

In [7]:
emp=np.empty((4,6))

In [8]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34598246e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 7.56602523e-307,
        1.29061821e-306, 1.11261298e-306, 9.34604358e-307]])

In [14]:
emp_like=np.empty_like(lspace)

In [16]:
emp_like

array([1., 2., 3., 4.])

In [18]:
ide=np.identity(45)

In [19]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [20]:
ide.shape

(45, 45)

In [21]:
ide.size

2025

In [23]:
rng=np.arange(100)


In [24]:
rng


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [33]:
arr=rng.reshape(2,50)

In [34]:
arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [35]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [37]:
arr=np.array(x)

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr.sum(axis=0)

array([12, 15, 18])

In [40]:
arr.sum(axis=1)

array([ 6, 15, 24])

# tranpose

In [41]:
arr.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

***flat***

In [42]:
arr.flat

In [47]:
for item in arr.flat:
  print(item)

1
2
3
4
5
6
7
8
9


In [48]:
arr.ndim

2

In [49]:
arr.shape

(3, 3)

In [50]:
arr.size

9

In [51]:
arr.nbytes


36

In [52]:
one=np.array([1,5,2,8,88])

In [53]:
one.argmax()

4

In [54]:
one.argmin()


0

In [55]:
one.argsort()

array([0, 2, 1, 3, 4], dtype=int64)

In [58]:
np.sqrt(one)

array([1.        , 2.23606798, 1.41421356, 2.82842712, 9.38083152])

In [59]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
np.where(arr>6)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [62]:
type(np.where(arr>6))

tuple